/*******************************************************************************
 * Copyright (c) 2026 Carsten Hammer.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package org.sandbox.jdt.ui.tests.quickfix;

import org.eclipse.core.runtime.CoreException;
import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.jdt.core.IPackageFragment;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.sandbox.jdt.internal.corext.fix2.MYCleanUpConstants;
import org.sandbox.jdt.ui.tests.quickfix.rules.EclipseJava9;

/** Verifies conflict-free names generated by the Platform Status cleanup. */
public class PlatformStatusImportConflictTest {

	@RegisterExtension
	EclipseJava9 context= new EclipseJava9();

	@Test
	public void qualifiesIStatusWhenTheSimpleNameIsOccupied() throws CoreException {
		IPackageFragment pack= context.getSourceFolder().createPackageFragment("test1", false, null); //$NON-NLS-1$
		ICompilationUnit unit= pack.createCompilationUnit("E1.java", //$NON-NLS-1$
				"""
				package test1;
				import org.eclipse.core.runtime.MultiStatus;
				public class E1 {
					static class IStatus {
					}
					MultiStatus status = new MultiStatus("plugin.id", 0, "important message", null);
				}
				""", false, null);

		context.enable(MYCleanUpConstants.SIMPLIFY_STATUS_CLEANUP);
		context.assertRefactoringResultAsExpected(new ICompilationUnit[] { unit }, new String[] { """
				package test1;
				import org.eclipse.core.runtime.MultiStatus;
				public class E1 {
					static class IStatus {
					}
					MultiStatus status = new MultiStatus("plugin.id", org.eclipse.core.runtime.IStatus.OK, "important message", null);
				}
				""" }, null);
	}
}
