---
# Exclude build artifacts, configuration, and binary files
exclude_paths:
  - "target/**"
  - ".git/**"
  - ".github/**"
  - "**/*.class"
  - "**/*.jar"
  - "**/*.war"
  - "**/*.ear"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.gif"
  - "**/*.svg"
  - "**/*.ico"
  - "**/*.pdf"
  - "**/*.ttf"
  - "**/*.woff*"
  - "**/resources/**"

# Include Java sources from Eclipse plugin structure
# Java files are in: sandbox_*/src/org/sandbox/...
include_paths:
  - "sandbox_*/src/**/*.java"

# (Optional) Tool-spezifisches Tuning – Namen laut Doku
engines:
  pmd: {}
  checkstyle: {}
  spotbugs: {}