---
# Exclude build artifacts, configuration, and binary files
exclude_paths:
  - "target/**"
  - ".git/**"
  - ".github/**"
  - "bin/**"
  - "p2/**"
  - "build/**"
  - "generated/**"
  - "sandbox1.2.1/**"
  - "plugins/**"
  - "features/**"
  - "**/testresources/**"
  - "**/*.class"
  - "**/*.jar"
  - "**/*.war"
  - "**/*.ear"
  - "**/*.zip"
  - "**/*.tar.gz"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/*.svg"
  - "**/*.ico"
  - "**/*.pdf"
  - "**/*.ttf"
  - "**/*.woff*"
  - "**/*.eot"
  - "**/resources/**"
  - "artifacts.jar"
  - "content.jar"

# Only analyze Java sources in src directories
include_paths:
  - "*/src/**/*.java"
  - "src/**/*.java"

# Tool-specific configuration
engines:
  pmd:
    enabled: true
    exclude_patterns:
      - "**/*.class"
      - "**/*.jar"
      - "**/target/**"
      - "**/bin/**"
      - "**/testresources/**"
  checkstyle:
    enabled: true
  spotbugs:
    enabled: true