---
# Exclude build artifacts, configuration, and binary files
exclude_paths:
  - "target/**"
  - ".git/**"
  - ".github/**"
  - "**/*.class"
  - "**/*.jar"
  - "**/*.war"
  - "**/*.ear"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.gif"
  - "**/*.svg"
  - "**/*.ico"
  - "**/*.pdf"
  - "**/*.ttf"
  - "**/*.woff*"
  - "**/resources/**"

# Only analyze Java sources
include_paths:
  - "src/**/*.java"

# (Optional) Tool-spezifisches Tuning – Namen laut Doku
engines:
  pmd: {}
  checkstyle: {}
  spotbugs: {}