/*******************************************************************************
 * Copyright (c) 2026 Carsten Hammer.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Carsten Hammer - initial API and implementation
 *******************************************************************************/
package org.sandbox.jdt.triggerpattern.test.policy;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import java.util.stream.Stream;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

/**
 * Maven entry point for evidence generated by the retained JDT UI workspace
 * runner.
 *
 * @since 1.3.5
 */
public class JdtUiCorpusEvidenceTest {

	private static final String PREFIX = "sandbox.jdt.ui.corpus."; //$NON-NLS-1$
	private static final String REPOSITORY = PREFIX + "repository"; //$NON-NLS-1$
	private static final String BASELINE_SOURCES = PREFIX + "baselineSources"; //$NON-NLS-1$
	private static final String MODE = PREFIX + "mode"; //$NON-NLS-1$
	private static final String CHANGED_FILES = PREFIX + "changedFiles"; //$NON-NLS-1$
	private static final String CHECK_REPORT = PREFIX + "checkReport"; //$NON-NLS-1$
	private static final String APPLY_REPORT = PREFIX + "applyReport"; //$NON-NLS-1$
	private static final String OUTPUT = PREFIX + "output"; //$NON-NLS-1$

	@Test
	public void verifiesConfiguredRetainedWorkspaceEvidence() throws Exception {
		String repositoryValue = System.getProperty(REPOSITORY);
		String baselineValue = System.getProperty(BASELINE_SOURCES);
		String modeValue = System.getProperty(MODE);
		String changedFilesValue = System.getProperty(CHANGED_FILES);
		String checkReportValue = System.getProperty(CHECK_REPORT);
		String applyReportValue = System.getProperty(APPLY_REPORT);
		String outputValue = System.getProperty(OUTPUT);
		boolean configured = Stream.of(repositoryValue, baselineValue, modeValue, changedFilesValue,
				checkReportValue, applyReportValue, outputValue).anyMatch(Objects::nonNull);
		Assumptions.assumeTrue(configured,
				"External pinned JDT UI evidence was not configured for this Maven run"); //$NON-NLS-1$
		assertConfigured(REPOSITORY, repositoryValue);
		assertConfigured(BASELINE_SOURCES, baselineValue);
		assertConfigured(MODE, modeValue);
		assertConfigured(CHANGED_FILES, changedFilesValue);
		assertConfigured(CHECK_REPORT, checkReportValue);
		assertConfigured(APPLY_REPORT, applyReportValue);
		assertConfigured(OUTPUT, outputValue);

		Path root = repositoryRoot();
		JdtUiCorpusEvidenceVerifier.Request request = new JdtUiCorpusEvidenceVerifier.Request(
				path(repositoryValue),
				path(baselineValue),
				root.resolve("qa/upstream-jdt/jdt-ui-junit4-corpus.json"), //$NON-NLS-1$
				JdtUiCorpusEvidenceVerifier.Mode.parse(modeValue),
				path(changedFilesValue),
				path(checkReportValue),
				path(applyReportValue),
				path(outputValue));
		JdtUiCorpusEvidenceVerifier.Result result = JdtUiCorpusEvidenceVerifier.verify(request);

		assertEquals("https://github.com/eclipse-jdt/eclipse.jdt.ui.git", //$NON-NLS-1$
				result.contract().repository());
		assertEquals("R4_40", result.contract().ref()); //$NON-NLS-1$
		assertEquals("c922f757b27b7e2b6215db383cec5f8aafd13227", //$NON-NLS-1$
				result.contract().commit());
		assertEquals("org.eclipse.jdt.ui.tests", result.contract().project()); //$NON-NLS-1$
		assertEquals(JdtUiCorpusEvidenceVerifier.Mode.parse(modeValue), result.mode());
	}

	private static void assertConfigured(String name, String value) {
		assertNotNull(value, () -> "All sandbox.jdt.ui.corpus.* properties must be configured together; missing " //$NON-NLS-1$
				+ name);
	}

	private static Path path(String value) {
		return Path.of(value).toAbsolutePath().normalize();
	}

	private static Path repositoryRoot() {
		Path candidate = Path.of("").toAbsolutePath().normalize(); //$NON-NLS-1$
		while (candidate != null) {
			if (Files.isRegularFile(candidate.resolve("pom.xml")) //$NON-NLS-1$
					&& Files.isDirectory(candidate.resolve("qa/upstream-jdt"))) { //$NON-NLS-1$
				return candidate;
			}
			candidate = candidate.getParent();
		}
		throw new IllegalStateException("Could not locate the Sandbox repository root"); //$NON-NLS-1$
	}
}
