/*******************************************************************************
 * Copyright (c) 2026 Carsten Hammer and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package org.eclipse.jgit.server.config;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Properties;

import org.junit.Test;

import io.github.carstenartur.jgit.storage.hibernate.schema.LegacyCoreSchemaAdoptionException;

/** Tests the read-only server maintenance boundary for legacy Core adoption. */
public class LegacyCoreSchemaPreflightTest {

	@Test
	public void reportsSupportedLegacySchemaWithoutRunningHibernate() throws Exception {
		String url= "jdbc:hsqldb:mem:legacy_preflight"; //$NON-NLS-1$
		try (Connection connection= DriverManager.getConnection(url, "SA", "")) { //$NON-NLS-1$ //$NON-NLS-2$
			createLegacySchema(connection);
			insertPack(connection, "demo", "pack-a", "pack", new byte[] { 1, 2, 3 }); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$

			LegacyCoreSchemaPreflight.PreflightReport report= LegacyCoreSchemaPreflight.inspect(connection);

			assertTrue(report.requiresAdoption());
			assertEquals(1, report.packRows());
			assertEquals(0, report.incompletePackRows());
			assertTrue(report.duplicatePackIdentities().isEmpty());
			assertTrue(LegacyCoreSchemaPreflight.toJson(report).contains("\"requiresAdoption\":true")); //$NON-NLS-1$
		}
	}

	@Test
	public void acceptsPublishedSqlServerAdoptionPathWithoutOpeningConnection() {
		LegacyCoreSchemaPreflight.requirePublishedLegacyAdoptionPath(
				"jdbc:sqlserver://localhost:1433;databaseName=sandbox"); //$NON-NLS-1$
	}

	@Test
	public void rejectsDatabaseWithoutPublishedLegacyAdoptionMigration() {
		Properties properties= connectionProperties("jdbc:h2:mem:unsupported-preflight"); //$NON-NLS-1$

		IllegalArgumentException failure= assertThrows(IllegalArgumentException.class,
				() -> LegacyCoreSchemaPreflight.inspect(properties));

		assertTrue(failure.getMessage().contains("PostgreSQL, HSQLDB or SQL Server")); //$NON-NLS-1$
	}

	@Test
	public void rejectsHsqldbUrlThatCouldCreateANewDatabase() {
		Properties properties= connectionProperties("jdbc:hsqldb:file:/tmp/missing-preflight-database"); //$NON-NLS-1$

		IllegalArgumentException failure= assertThrows(IllegalArgumentException.class,
				() -> LegacyCoreSchemaPreflight.inspect(properties));

		assertTrue(failure.getMessage().contains("ifexists=true")); //$NON-NLS-1$
	}

	@Test
	public void rejectsDuplicateLogicalPackIdentitiesWithoutChangingRows() throws Exception {
		String url= "jdbc:hsqldb:mem:legacy_preflight_duplicates"; //$NON-NLS-1$
		try (Connection connection= DriverManager.getConnection(url, "SA", "")) { //$NON-NLS-1$ //$NON-NLS-2$
			createLegacySchema(connection);
			insertPack(connection, "demo", "pack-a", "pack", new byte[] { 1 }); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
			insertPack(connection, "demo", "pack-a", "pack", new byte[] { 2 }); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$

			assertThrows(LegacyCoreSchemaAdoptionException.class,
					() -> LegacyCoreSchemaPreflight.inspect(connection));
			assertEquals(2, countPacks(connection));
		}
	}

	private static Properties connectionProperties(String url) {
		boolean hsqldb= url.startsWith("jdbc:hsqldb:"); //$NON-NLS-1$
		Properties properties= new Properties();
		properties.setProperty("hibernate.connection.url", url); //$NON-NLS-1$
		properties.setProperty("hibernate.connection.username", hsqldb ? "SA" : "sa"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
		properties.setProperty("hibernate.connection.password", ""); //$NON-NLS-1$ //$NON-NLS-2$
		properties.setProperty("hibernate.connection.driver_class", //$NON-NLS-1$
				hsqldb ? "org.hsqldb.jdbc.JDBCDriver" : "org.h2.Driver"); //$NON-NLS-1$ //$NON-NLS-2$
		return properties;
	}

	private static void createLegacySchema(Connection connection) throws SQLException {
		try (Statement statement= connection.createStatement()) {
			statement.execute("""
					create table git_packs (
						id bigint generated by default as identity primary key,
						repository_name varchar(255) not null,
						pack_name varchar(255) not null,
						pack_extension varchar(255) not null,
						data blob not null,
						file_size bigint not null,
						created_at timestamp not null
					)
					"""); //$NON-NLS-1$
		}
	}

	private static void insertPack(Connection connection, String repositoryName, String packName,
			String extension, byte[] data) throws SQLException {
		try (PreparedStatement statement= connection.prepareStatement(
				"insert into git_packs " //$NON-NLS-1$
						+ "(repository_name, pack_name, pack_extension, data, file_size, created_at) " //$NON-NLS-1$
						+ "values (?, ?, ?, ?, ?, ?)")) { //$NON-NLS-1$
			statement.setString(1, repositoryName);
			statement.setString(2, packName);
			statement.setString(3, extension);
			statement.setBytes(4, data);
			statement.setLong(5, data.length);
			statement.setTimestamp(6, Timestamp.from(Instant.parse("2026-07-28T00:00:00Z"))); //$NON-NLS-1$
			statement.executeUpdate();
		}
	}

	private static long countPacks(Connection connection) throws SQLException {
		try (Statement statement= connection.createStatement();
				var result= statement.executeQuery("select count(*) from git_packs")) { //$NON-NLS-1$
			result.next();
			return result.getLong(1);
		}
	}
}
