from pathlib import Path
import shutil
import sys
root = Path(sys.argv[1])
control = Path(__file__).parent
package = root / 'sandbox_math_cleanup/src/org/sandbox/jdt/internal/corext/fix/math'
shutil.copyfile(control/'MathSearchDerivation.java', package/'MathSearchDerivation.java')
p = package/'MathExplanation.java'
s = p.read_text()
old = '|| !verified.assumptions().equals(request.assumptions()))'
new = '|| !verified.assumptions().equals(request.assumptions())\n                || !verified.derivation().equals(candidate.derivation()))'
assert s.count(old) == 1
s = s.replace(old, new)
old = '        lines.add("Value graphs are not a step-by-step search proof; the original trace still governs exceptions and evaluation order.");'
new = '''        MathSearchDerivation.append(lines, verified, request, region, options, cancellation, MAXIMUM_TEXT_LENGTH);'''
assert s.count(old) == 1
p.write_text(s.replace(old, new))
p = root/'sandbox_math_cleanup_help/html/cleanup.html'
s = p.read_text()
addition = '''\n<h2>Recorded mathematical search steps</h2>
<p>The explanation includes the selected Regelsuche search path: each step names the
actual rule and displays the resulting computation using your Java variable names.
The SDK checks the contiguous path, regenerates its rule applications and independently
checks its numeric equivalence before Sandbox presents it. No target formula or
source-specific mathematical task is supplied by this view.</p>
<p>A compound proposal remains one recorded search step; it is not expanded into
unrecorded primitive identities. Legacy candidates without a recorded path are explicitly
identified. The original Java evaluation trace, numerical profile, guards and fallback
remain authoritative. Estimated work is not a timing measurement.</p>
<p>The existing Source explanations setting controls Java comments. Detailed diagnostics
and JSON reports retain the same selected path when source comments are disabled.
Cancellation or an oversized explanation never produces a silently truncated path.</p>
'''
assert s.count('</body>') == 1
p.write_text(s.replace('</body>', addition+'\n</body>'))
p = root/'docs/qa/selected-search-path.md'
p.parent.mkdir(parents=True, exist_ok=True)
p.write_text('''# Selected mathematical search paths in Java explanations\n\nSandbox renders the actual retained SDK search witness, using existing typed Java\nemission and source bindings. Mathematical rule selection and independent edge replay\nremain in Regelsuche. No named-problem recognizer, new algebra rule or second search\nfrontier is added.\n\nEvery retained step is numbered and identifies the actual generator rule. Compound\nproposals remain compound. Empty recorded paths and absent legacy history are distinct;\nneither is replaced by a fabricated derivation. Source comments are optional and the\nfull detailed explanation remains available in diagnostics and JSON. The original\nexception/evaluation trace, source guards, numeric contracts and exact Undo remain\nunchanged. Text is bounded and cancellation propagates without partial replacements.\n\nThe test-only revision ef3596b4622aa0c433fc86333477e08b45b20775 ran 220 standard\nmathematics tests: the existing 216 passed and four new integration tests failed only\non the missing path. Run 38046634580 preserves that red evidence. The new tests use\nordinary Java expressions, multistatement dataflow and differently named helpers;\nno expected result is passed to the optimizer. They compile original and generated\nJava, compare Cartesian integral boundary inputs and verify byte-exact Undo.\n\nThe SDK pin and distribution receipts must be generated by the repository-owned\ndistribution contract, not relabelled from an older binary. Native Help regeneration\nis required for the new loaded artifact fingerprints. Whole-repository CI and review\nremain separate gates; this document is not itself a success receipt.\n''')
print('Staged Java presentation of SDK-selected search edges; no mathematical processing added in sandbox.')
