/*******************************************************************************
 * Copyright (c) 2021 Alexandru Gyori and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Alexandru Gyori original code
 *     Carsten Hammer initial port to Eclipse
 *******************************************************************************/
package org.sandbox.jdt.ui.tests.quickfix;

import org.eclipse.jdt.core.ICompilationUnit;
import org.eclipse.jdt.core.IPackageFragment;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.junit.jupiter.params.provider.ValueSource;
import org.sandbox.jdt.internal.corext.fix.MYCleanUpConstants;
import org.sandbox.jdt.ui.tests.quickfix.rules.AbstractEclipseJava;
import org.sandbox.jdt.ui.tests.quickfix.rules.EclipseJava8;

public class Java8CleanUpTest {
		
	@RegisterExtension
	AbstractEclipseJava context= new EclipseJava8();
	
	enum UseFunctionalLoop {
		SIMPLECONVERT("package test1;\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "class TestDemo {\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "    public void test(List<Integer> ls) {\n"
                + "        for (Integer l : ls)\n"
                + "            System.out.println(l);\n"
                + "    }\n"
                + "}",

                "package test1;\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "class TestDemo {\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "    public void test(List<Integer> ls) {\n"
                        + "        ls.forEach(l -> System.out.println(l));\n"
                        + "    }\n"
                        + "}"),

		CHAININGMAP("package test1;\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "class TestDemo {\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "    public void test(List<Integer> ls) {\n"
                + "        for (Integer l : ls) {\n"
                + "            String s = l.toString();\n"
                + "            System.out.println(s);\n"
                + "        }\n"
                + "    }\n"
                + "}",
				
                "package test1;\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "class TestDemo {\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "    public void test(List<Integer> ls) {\n"
                        + "        ls.stream().map(l -> l.toString()).forEachOrdered(s -> {\n"
                        + "            System.out.println(s);\n"
                        + "        });\n"
                        + "    }\n"
                        + "}"),

		DOUBLEINCREMENTREDUCER("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class TestDemo {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public static void main( String[] args) {\n"
                + "        // TODO code application logic here\n"
                + "        List<Integer> ints=new ArrayList<>();\n"
                + "        double len=0.;        \n"
                + "        for(int i : ints)\n"
                + "            len++;\n"
                + "            \n"
                + "    }    \n"
                + "}",
				
               "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public static void main( String[] args) {\n"
                        + "        // TODO code application logic here\n"
                        + "        List<Integer> ints=new ArrayList<>();\n"
                        + "        double len=0.;        \n"
                        + "        len = ints.stream().map(_item -> 1.0).reduce(len, (accumulator, _item) -> accumulator + 1);\n"
                        + "            \n"
                        + "    }    \n"
                        + "}"),
		ChainingFilterMapForEachConvert("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "\n"
                + "    public void test(List<Integer> ls) {        \n"
                + "        for (Integer l : ls) {\n"
                + "            if(l!=null)\n"
                + "            {\n"
                + "                String s = l.toString();\n"
                + "                System.out.println(s);\n"
                + "            }\n"
                + "        }\n"
                + "            \n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public void test(List<Integer> ls) {        \n"
                        + "        ls.stream().filter(l -> (l!=null)).map(l -> l.toString()).forEachOrdered(s -> {\n"
                        + "            System.out.println(s);\n"
                        + "        });\n"
                        + "            \n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		SmoothLongerChaining("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1,2,3));\n"
                + "    }\n"
                + "\n"
                + "    public void test(List<Integer> ls) {        \n"
                + "        for (Integer a : ls) {\n"
                + "            Integer l = new Integer(a.intValue());\n"
                + "            if(l!=null)\n"
                + "            {\n"
                + "                String s = l.toString();\n"
                + "                System.out.println(s);\n"
                + "            }\n"
                + "        }\n"
                + "            \n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1,2,3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public void test(List<Integer> ls) {        \n"
                        + "        ls.stream().map(a -> new Integer(a.intValue())).filter(l -> (l!=null)).map(l -> l.toString()).forEachOrdered(s -> {\n"
                        + "            System.out.println(s);\n"
                        + "        });\n"
                        + "            \n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		NonFilteringIfChaining("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1,2,3));\n"
                + "    }\n"
                + "\n"
                + "    public void test(List<Integer> ls) {        \n"
                + "        for (Integer a : ls) {\n"
                + "            Integer l = new Integer(a.intValue());\n"
                + "            if(l!=null)\n"
                + "            {                \n"
                + "                String s = l.toString();\n"
                + "                if(s!=null)\n"
                + "                    System.out.println(s);\n"
                + "                System.out.println(\"cucu\");\n"
                + "            }\n"
                + "        }\n"
                + "            \n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1,2,3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public void test(List<Integer> ls) {        \n"
                        + "        ls.stream().map(a -> new Integer(a.intValue())).filter(l -> (l!=null)).map(l -> l.toString()).map(s -> {\n"
                        + "            if(s!=null)\n"
                        + "                System.out.println(s);\n"
                        + "            return s;\n"
                        + "        }).forEachOrdered(_item -> {\n"
                        + "            System.out.println(\"cucu\");\n"
                        + "        });\n"
                        + "            \n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		ContinuingIfFilterSingleStatement("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "\n"
                + "    public void test(List<Integer> ls) {\n"
                + "        for (Integer l : ls) {            \n"
                + "            if (l == null) {\n"
                + "                continue;\n"
                + "            }\n"
                + "            String s = l.toString();\n"
                + "            if (s != null) {\n"
                + "                System.out.println(s);\n"
                + "            }     \n"
                + "\n"
                + "        }\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public void test(List<Integer> ls) {\n"
                        + "        ls.stream().filter(l -> !(l == null)).map(l -> l.toString()).filter(s -> (s != null)).forEachOrdered(s -> {\n"
                        + "            System.out.println(s);\n"
                        + "        });\n"
                        + "\n"
                        + "\n"
                        + "    }\n"
                        + "}"),
		ChainedAnyMatch("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "\n"
                + "    public Boolean test(List<Integer> ls) {\n"
                + "        for(Integer l:ls)\n"
                + "        {\n"
                + "            String s = l.toString();\n"
                + "            Object o = foo(s);\n"
                + "            if(o==null)\n"
                + "                return true;\n"
                + "        }\n"
                + "        \n"
                + "        return false;\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "    \n"
                + "    Object foo(Object o)\n"
                + "    {\n"
                + "        return o;\n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public Boolean test(List<Integer> ls) {\n"
                        + "        if (ls.stream().map(l -> l.toString()).map(s -> foo(s)).anyMatch(o -> (o==null))) {\n"
                        + "            return true;\n"
                        + "        }\n"
                        + "        \n"
                        + "        return false;\n"
                        + "\n"
                        + "\n"
                        + "    }\n"
                        + "    \n"
                        + "    Object foo(Object o)\n"
                        + "    {\n"
                        + "        return o;\n"
                        + "    }\n"
                        + "}"),
		ChainedNoneMatch("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "\n"
                + "    public Boolean test(List<Integer> ls) {\n"
                + "        for(Integer l:ls)\n"
                + "        {\n"
                + "            String s = l.toString();\n"
                + "            Object o = foo(s);\n"
                + "            if(o==null)\n"
                + "                return false;\n"
                + "        }\n"
                + "        \n"
                + "        return true;\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "    \n"
                + "    Object foo(Object o)\n"
                + "    {\n"
                + "        return o;\n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public Boolean test(List<Integer> ls) {\n"
                        + "        if (!ls.stream().map(l -> l.toString()).map(s -> foo(s)).noneMatch(o -> (o==null))) {\n"
                        + "            return false;\n"
                        + "        }\n"
                        + "        \n"
                        + "        return true;\n"
                        + "\n"
                        + "\n"
                        + "    }\n"
                        + "    \n"
                        + "    Object foo(Object o)\n"
                        + "    {\n"
                        + "        return o;\n"
                        + "    }\n"
                        + "}"),
		NoNeededVariablesMerging("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) throws Exception {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                + "    }\n"
                + "\n"
                + "   \n"
                + "    public Boolean test(List<Integer> ls) throws Exception {\n"
                + "        Integer i=0;        \n"
                + "        for(Integer l : ls)\n"
                + "        {         \n"
                + "            System.out.println();\n"
                + "            System.out.println(\"\");\n"
                + "            \n"
                + "        }\n"
                + "        System.out.println(i);\n"
                + "        return false;\n"
                + "\n"
                + "\n"
                + "    }    \n"
                + "    private void foo(Object o, int i) throws Exception\n"
                + "    {\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) throws Exception {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                        + "    }\n"
                        + "\n"
                        + "   \n"
                        + "    public Boolean test(List<Integer> ls) throws Exception {\n"
                        + "        Integer i=0;        \n"
                        + "        ls.stream().map(_item -> {         \n"
                        + "            System.out.println();\n"
                        + "            return _item;\n"
                        + "        }).forEachOrdered(_item -> {\n"
                        + "            System.out.println(\"\");\n"
                        + "        });\n"
                        + "        System.out.println(i);\n"
                        + "        return false;\n"
                        + "\n"
                        + "\n"
                        + "    }    \n"
                        + "    private void foo(Object o, int i) throws Exception\n"
                        + "    {\n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		SomeChainingWithNoNeededVar("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                + "    }\n"
                + "\n"
                + "    public Boolean test(List<Integer> ls) {\n"
                + "        for(Integer a:ls)\n"
                + "        {\n"
                + "            Integer l = new Integer(a.intValue());\n"
                + "            if(l==null)\n"
                + "            {\n"
                + "                String s=l.toString();\n"
                + "                if(s!=null)\n"
                + "                {\n"
                + "                    System.out.println(s);\n"
                + "                }\n"
                + "                System.out.println(\"cucu\");\n"
                + "            }   \n"
                + "            System.out.println();\n"
                + "        }\n"
                + "        \n"
                + "        return true;\n"
                + "\n"
                + "\n"
                + "    }\n"
                + "        \n"
                + "    Object foo(Object o)\n"
                + "    {\n"
                + "        return o;\n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3));\n"
                        + "    }\n"
                        + "\n"
                        + "    public Boolean test(List<Integer> ls) {\n"
                        + "        ls.stream().map(a -> new Integer(a.intValue())).map(l -> {\n"
                        + "            if(l==null)\n"
                        + "            {\n"
                        + "                String s=l.toString();\n"
                        + "                if(s!=null)\n"
                        + "                {\n"
                        + "                    System.out.println(s);\n"
                        + "                }\n"
                        + "                System.out.println(\"cucu\");\n"
                        + "            }   \n"
                        + "            return l;\n"
                        + "        }).forEachOrdered(_item -> {\n"
                        + "            System.out.println();\n"
                        + "        });\n"
                        + "        \n"
                        + "        return true;\n"
                        + "\n"
                        + "\n"
                        + "    }\n"
                        + "        \n"
                        + "    Object foo(Object o)\n"
                        + "    {\n"
                        + "        return o;\n"
                        + "    }\n"
                        + "}"),
		SimpleReducer("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                + "    }\n"
                + "\n"
                + "   \n"
                + "    public Boolean test(List<Integer> ls) {\n"
                + "        Integer i=0;\n"
                + "        for(Integer l : ls)\n"
                + "            i++;\n"
                + "        System.out.println(i);\n"
                + "        return true;\n"
                + "\n"
                + "\n"
                + "    }    \n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                        + "    }\n"
                        + "\n"
                        + "   \n"
                        + "    public Boolean test(List<Integer> ls) {\n"
                        + "        Integer i=0;\n"
                        + "        i = ls.stream().map(_item -> 1).reduce(i, Integer::sum);\n"
                        + "        System.out.println(i);\n"
                        + "        return true;\n"
                        + "\n"
                        + "\n"
                        + "    }    \n"
                        + "}"),
		ChainedReducer("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                + "    }\n"
                + "\n"
                + "   \n"
                + "    public Boolean test(List<Integer> ls) {\n"
                + "        Integer i=0;\n"
                + "        for(Integer l : ls)\n"
                + "        {             \n"
                + "            if(l!=null)\n"
                + "            {\n"
                + "                foo(l);\n"
                + "                i++;\n"
                + "            }\n"
                + "            \n"
                + "        }\n"
                + "        System.out.println(i);\n"
                + "        return true;\n"
                + "\n"
                + "\n"
                + "    }    \n"
                + "    private void foo(Object o)\n"
                + "    {\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                        + "    }\n"
                        + "\n"
                        + "   \n"
                        + "    public Boolean test(List<Integer> ls) {\n"
                        + "        Integer i=0;\n"
                        + "        i = ls.stream().filter(l -> (l!=null)).map(l -> {\n"
                        + "            foo(l);\n"
                        + "            return l;\n"
                        + "        }).map(_item -> 1).reduce(i, Integer::sum);\n"
                        + "        System.out.println(i);\n"
                        + "        return true;\n"
                        + "\n"
                        + "\n"
                        + "    }    \n"
                        + "    private void foo(Object o)\n"
                        + "    {\n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		ChainedReducerWithMerging("package test1;\n"
                + "\n"
                + "import java.util.Arrays;\n"
                + "import java.util.List;\n"
                + "\n"
                + "class TestDemo {\n"
                + "\n"
                + "    public static void main(String[] args) {\n"
                + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                + "    }\n"
                + "\n"
                + "   \n"
                + "    public Boolean test(List<Integer> ls) {\n"
                + "        Integer i=0;\n"
                + "        for(Integer l : ls)\n"
                + "        {        \n"
                + "            String s =l.toString();\n"
                + "            System.out.println(s);\n"
                + "            foo(l);\n"
                + "            if(l!=null)\n"
                + "            {\n"
                + "                foo(l);                \n"
                + "                i--;\n"
                + "            }\n"
                + "            \n"
                + "        }\n"
                + "        System.out.println(i);\n"
                + "        return true;\n"
                + "\n"
                + "\n"
                + "    }    \n"
                + "    private void foo(Object o)\n"
                + "    {\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.Arrays;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    public static void main(String[] args) {\n"
                        + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                        + "    }\n"
                        + "\n"
                        + "   \n"
                        + "    public Boolean test(List<Integer> ls) {\n"
                        + "        Integer i=0;\n"
                        + "        i = ls.stream().map(l -> {        \n"
                        + "            String s =l.toString();\n"
                        + "            System.out.println(s);\n"
                        + "            foo(l);\n"
                        + "            return l;\n"
                        + "        }).filter(l -> (l!=null)).map(l -> {\n"
                        + "            foo(l);\n"
                        + "            return l;\n"
                        + "        }).map(_item -> 1).reduce(i, (accumulator, _item) -> accumulator - 1);\n"
                        + "        System.out.println(i);\n"
                        + "        return true;\n"
                        + "\n"
                        + "\n"
                        + "    }    \n"
                        + "    private void foo(Object o)\n"
                        + "    {\n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		IncrementReducer("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class TestDemo {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public static void main( String[] args) {\n"
                + "        List<Integer> ls = new ArrayList<>();\n"
                + "        int i =0;\n"
                + "        for ( Integer l : ls) {\n"
                + "            i+=1;        \n"
                + "        }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    private static void foo(Integer l) {\n"
                + "        throw new UnsupportedOperationException(\"Not supported yet.\"); //To change body of generated methods, choose Tools | Templates.\n"
                + "    }\n"
                + "}\n"
                + "",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public static void main( String[] args) {\n"
                        + "        List<Integer> ls = new ArrayList<>();\n"
                        + "        int i =0;\n"
                        + "        i = ls.stream().map(_item -> 1).reduce(i, Integer::sum);\n"
                        + "\n"
                        + "    }\n"
                        + "\n"
                        + "    private static void foo(Integer l) {\n"
                        + "        throw new UnsupportedOperationException(\"Not supported yet.\"); //To change body of generated methods, choose Tools | Templates.\n"
                        + "    }\n"
                        + "}\n"
                        + ""),
		AccumulatingMapReduce("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class TestDemo {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public static void main( String[] args) {\n"
                + "        List<Integer> ls = new ArrayList<>();\n"
                + "        int i =0;\n"
                + "        for ( Integer l : ls) {\n"
                + "            i+=foo(l);        \n"
                + "        }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    private static int foo(Integer l) {\n"
                + "        throw new UnsupportedOperationException(\"Not supported yet.\"); //To change body of generated methods, choose Tools | Templates.\n"
                + "    }\n"
                + "}\n"
                + "",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public static void main( String[] args) {\n"
                        + "        List<Integer> ls = new ArrayList<>();\n"
                        + "        int i =0;\n"
                        + "        i = ls.stream().map(l -> foo(l)).reduce(i, Integer::sum);\n"
                        + "\n"
                        + "    }\n"
                        + "\n"
                        + "    private static int foo(Integer l) {\n"
                        + "        throw new UnsupportedOperationException(\"Not supported yet.\"); //To change body of generated methods, choose Tools | Templates.\n"
                        + "    }\n"
                        + "}\n"
                        + ""),
		StringConcat("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class TestDemo {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public static void main( String[] args) {\n"
                + "        List<Integer> ls = new ArrayList<>();\n"
                + "        String i =\"\";\n"
                + "        for ( Integer l : ls) {\n"
                + "            i+=foo(l);        \n"
                + "        }\n"
                + "\n"
                + "    }\n"
                + "\n"
                + "    private static String foo(Integer l) {\n"
                + "        throw new UnsupportedOperationException(\"Not supported yet.\"); //To change body of generated methods, choose Tools | Templates.\n"
                + "    }\n"
                + "}\n"
                + "",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class TestDemo {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public static void main( String[] args) {\n"
                        + "        List<Integer> ls = new ArrayList<>();\n"
                        + "        String i =\"\";\n"
                        + "        i = ls.stream().map(l -> foo(l)).reduce(i, String::concat);\n"
                        + "\n"
                        + "    }\n"
                        + "\n"
                        + "    private static String foo(Integer l) {\n"
                        + "        throw new UnsupportedOperationException(\"Not supported yet.\"); //To change body of generated methods, choose Tools | Templates.\n"
                        + "    }\n"
                        + "}\n"
                        + ""),
		MergingOperations("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class JavaApplication1 {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public boolean b() {\n"
                + "        // TODO code application logic here\n"
                + "        List<String> strs = new ArrayList<String>();\n"
                + "        int i = 0;\n"
                + "        int j = 0;\n"
                + "        for(String str: strs)\n"
                + "        {            \n"
                + "            int len1=str.length();\n"
                + "            int len2 = str.length();\n"
                + "            if(len1%2==0){\n"
                + "                len2++;\n"
                + "                System.out.println(len2);\n"
                + "                System.out.println();\n"
                + "            }\n"
                + "            \n"
                + "        }\n"
                + "        return false;\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
               "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class JavaApplication1 {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public boolean b() {\n"
                        + "        // TODO code application logic here\n"
                        + "        List<String> strs = new ArrayList<String>();\n"
                        + "        int i = 0;\n"
                        + "        int j = 0;\n"
                        + "        strs.forEach(str -> {            \n"
                        + "            int len1=str.length();\n"
                        + "            int len2 = str.length();\n"
                        + "            if (len1%2==0) {\n"
                        + "                len2++;\n"
                        + "                System.out.println(len2);\n"
                        + "                System.out.println();\n"
                        + "            }\n"
                        + "        });\n"
                        + "        return false;\n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		BeautificationWorks("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class JavaApplication1 {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public boolean b() {\n"
                + "        // TODO code application logic here\n"
                + "        List<String> strs = new ArrayList<String>();\n"
                + "        int i = 0;\n"
                + "        int j = 0;\n"
                + "        for(String str: strs)\n"
                + "        {            \n"
                + "            String s = \"foo\";\n"
                + "            s=s.toString();\n"
                + "            System.out.println(s);\n"
                + "            \n"
                + "        }\n"
                + "        return false;\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
               "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class JavaApplication1 {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public boolean b() {\n"
                        + "        // TODO code application logic here\n"
                        + "        List<String> strs = new ArrayList<String>();\n"
                        + "        int i = 0;\n"
                        + "        int j = 0;\n"
                        + "        strs.stream().map(_item -> \"foo\").map(s -> s.toString()).forEachOrdered(s -> {\n"
                        + "            System.out.println(s);\n"
                        + "        });\n"
                        + "        return false;\n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		BeautificationWorks2("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class JavaApplication1 {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public boolean b() {\n"
                + "        // TODO code application logic here\n"
                + "        List<String> strs = new ArrayList<String>();\n"
                + "        int i = 0;\n"
                + "        int j = 0;\n"
                + "        for(String str: strs)\n"
                + "        {            \n"
                + "            String s = \"foo\";\n"
                + "            s=s.toString();\n"
                + "            System.out.println();\n"
                + "            \n"
                + "        }\n"
                + "        return false;\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
               "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class JavaApplication1 {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public boolean b() {\n"
                        + "        // TODO code application logic here\n"
                        + "        List<String> strs = new ArrayList<String>();\n"
                        + "        int i = 0;\n"
                        + "        int j = 0;\n"
                        + "        strs.stream().map(_item -> \"foo\").map(s -> s.toString()).forEachOrdered(_item -> {\n"
                        + "            System.out.println();\n"
                        + "        });\n"
                        + "        return false;\n"
                        + "        \n"
                        + "    }\n"
                        + "}"),
		DecrementingReducer("package test1;\n"
                + "\n"
                + "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "\n"
                + "/**\n"
                + " *\n"
                + " * @author alexandrugyori\n"
                + " */\n"
                + "class JavaApplication1 {\n"
                + "\n"
                + "    /**\n"
                + "     * @param args the command line arguments\n"
                + "     */\n"
                + "    public boolean b() {\n"
                + "        // TODO code application logic here\n"
                + "        List<String> strs = new ArrayList<String>();\n"
                + "        int i = 0;\n"
                + "        int j = 0;\n"
                + "        for(String str : strs)\n"
                + "            i-=1;\n"
                + "        return false;\n"
                + "        \n"
                + "    }\n"
                + "}",
                				
                "package test1;\n"
                        + "\n"
                        + "import java.util.ArrayList;\n"
                        + "import java.util.List;\n"
                        + "\n"
                        + "/**\n"
                        + " *\n"
                        + " * @author alexandrugyori\n"
                        + " */\n"
                        + "class JavaApplication1 {\n"
                        + "\n"
                        + "    /**\n"
                        + "     * @param args the command line arguments\n"
                        + "     */\n"
                        + "    public boolean b() {\n"
                        + "        // TODO code application logic here\n"
                        + "        List<String> strs = new ArrayList<String>();\n"
                        + "        int i = 0;\n"
                        + "        int j = 0;\n"
                        + "        i = strs.stream().map(_item -> 1).reduce(i, (accumulator, _item) -> accumulator - _item);\n"
                        + "        return false;\n"
                        + "        \n"
                        + "    }\n"
                        + "}");
		
		UseFunctionalLoop(String given, String expected) {
			this.given=given;
			this.expected=expected;
		}

		String given, expected;
	}

	@Disabled
	@ParameterizedTest
	@EnumSource(UseFunctionalLoop.class)
	public void testExplicitEncodingParametrized(UseFunctionalLoop test) throws Exception {
		IPackageFragment pack= context.fSourceFolder.createPackageFragment("test1", false, null);
		ICompilationUnit cu= pack.createCompilationUnit("TestDemo.java", test.given, false, null);
		context.enable(MYCleanUpConstants.USEFUNCTIONALLOOP_CLEANUP);
		context.assertRefactoringResultAsExpected(new ICompilationUnit[] {cu}, new String[] {test.expected}, null);	
	}

	@Disabled
	@ParameterizedTest
	@ValueSource(strings = {
			/**
			 * WithArrays
			 */
            "package testdemo;\n"
            + "\n"
            + "import java.util.ArrayList;\n"
            + "import java.util.List;\n"
            + "\n"
            + "/**\n"
            + " *\n"
            + " * @author alexandrugyori\n"
            + " */\n"
            + "class TestDemo {\n"
            + "\n"
            + "    /**\n"
            + "     * @param args the command line arguments\n"
            + "     */\n"
            + "    public boolean b() {\n"
            + "        // TODO code application logic here\n"
            + "        String[] strs = new String[10];\n"
            + "        int i = 0;\n"
            + "        int j = 0;\n"
            + "        for(String str:strs)\n"
            + "            i++;\n"
            + "        return false;\n"
            + "        \n"
            + "    }\n"
            + "}",
            
            /**
             * NoHintDueToNEF
             */
            "package testdemo;\n"
                    + "\n"
                    + "import java.util.Arrays;\n"
                    + "import java.util.List;\n"
                    + "\n"
                    + "class TestDemo {\n"
                    + "\n"
                    + "    public static void main(String[] args) {\n"
                    + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                    + "    }\n"
                    + "\n"
                    + "   \n"
                    + "    public Boolean test(List<Integer> ls) {\n"
                    + "        Integer i=0;\n"
                    + "        for(Integer l : ls)\n"
                    + "        {        \n"
                    + "            String s =l.toString();\n"
                    + "            System.out.println(s);\n"
                    + "            foo(l,i);            \n"
                    + "            if(l!=null)\n"
                    + "            {                           \n"
                    + "                i++;\n"
                    + "            }\n"
                    + "            \n"
                    + "        }\n"
                    + "        System.out.println(i);\n"
                    + "        return true;\n"
                    + "\n"
                    + "\n"
                    + "    }    \n"
                    + "    private void foo(Object o, int i)\n"
                    + "    {\n"
                    + "        \n"
                    + "    }\n"
                    + "}",
                    
                    /**
                     * NoHintDueToBreak
                     */
                    "package testdemo;\n"
                            + "\n"
                            + "import java.util.Arrays;\n"
                            + "import java.util.List;\n"
                            + "\n"
                            + "class TestDemo {\n"
                            + "\n"
                            + "    public static void main(String[] args) {\n"
                            + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                            + "    }\n"
                            + "\n"
                            + "   \n"
                            + "    public Boolean test(List<Integer> ls) {\n"
                            + "        Integer i=0;\n"
                            + "        for(Integer l : ls)\n"
                            + "        {                      \n"
                            + "            if(l!=null)\n"
                            + "            {                           \n"
                            + "                break;\n"
                            + "            }\n"
                            + "            \n"
                            + "        }\n"
                            + "        System.out.println(i);\n"
                            + "        return true;\n"
                            + "\n"
                            + "\n"
                            + "    }    \n"
                            + "    private void foo(Object o, int i)\n"
                            + "    {\n"
                            + "        \n"
                            + "    }\n"
                            + "}",
                            
                            /**
                             * NoHintDueToReturnInt
                             */
                            "package testdemo;\n"
                                    + "\n"
                                    + "import java.util.Arrays;\n"
                                    + "import java.util.List;\n"
                                    + "\n"
                                    + "class TestDemo {\n"
                                    + "\n"
                                    + "    public static void main(String[] args) {\n"
                                    + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                                    + "    }\n"
                                    + "\n"
                                    + "   \n"
                                    + "    public int test(List<Integer> ls) {\n"
                                    + "        Integer i=0;\n"
                                    + "        for(Integer l : ls)\n"
                                    + "        {                      \n"
                                    + "            if(l!=null)\n"
                                    + "            {                           \n"
                                    + "                return 0;\n"
                                    + "            }\n"
                                    + "            \n"
                                    + "        }\n"
                                    + "        System.out.println(i);\n"
                                    + "        return 1;\n"
                                    + "\n"
                                    + "\n"
                                    + "    }    \n"
                                    + "    private void foo(Object o, int i)\n"
                                    + "    {\n"
                                    + "        \n"
                                    + "    }\n"
                                    + "}",
                                    
                                    /**
                                     * NoHintDueToMultipleReturnBoolean
                                     */
                                    "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.Arrays;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    public static void main(String[] args) {\n"
                                            + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                                            + "    }\n"
                                            + "\n"
                                            + "   \n"
                                            + "    public Boolean test(List<Integer> ls) {\n"
                                            + "        Integer i=0;\n"
                                            + "        for(Integer l : ls)\n"
                                            + "        {                      \n"
                                            + "            if(l==null)\n"
                                            + "            {                           \n"
                                            + "                return true;\n"
                                            + "            }\n"
                                            + "            if(l.toString()==null)\n"
                                            + "                return true;\n"
                                            + "            \n"
                                            + "        }\n"
                                            + "        System.out.println(i);\n"
                                            + "        return false;\n"
                                            + "\n"
                                            + "\n"
                                            + "    }    \n"
                                            + "    private void foo(Object o, int i)\n"
                                            + "    {\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}",
                                            
                                            /**
                                             * NoHintDueToLabeledContinue
                                             */
                                            "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.Arrays;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    public static void main(String[] args) {\n"
                                            + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                                            + "    }\n"
                                            + "\n"
                                            + "   \n"
                                            + "    public Boolean test(List<Integer> ls) {\n"
                                            + "        Integer i=0;\n"
                                            + "        label:\n"
                                            + "        for(Integer l : ls)\n"
                                            + "        {                      \n"
                                            + "            if(l==null)\n"
                                            + "            {                           \n"
                                            + "                continue label;\n"
                                            + "            }\n"
                                            + "            if(l.toString()==null)\n"
                                            + "                return true;\n"
                                            + "            \n"
                                            + "        }\n"
                                            + "        System.out.println(i);\n"
                                            + "        return false;\n"
                                            + "\n"
                                            + "\n"
                                            + "    }    \n"
                                            + "    private void foo(Object o, int i)\n"
                                            + "    {\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}",
                                            
                                            /**
                                             * NoHintDueToNonEliminableContinue
                                             */
                                            "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.Arrays;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    public static void main(String[] args) {\n"
                                            + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                                            + "    }\n"
                                            + "\n"
                                            + "   \n"
                                            + "    public Boolean test(List<Integer> ls) {\n"
                                            + "        Integer i=0;\n"
                                            + "        \n"
                                            + "        for(Integer l : ls)\n"
                                            + "        {                      \n"
                                            + "            if(l==null)\n"
                                            + "            {                           \n"
                                            + "                continue;\n"
                                            + "            }\n"
                                            + "            else if(l.toString()==null)\n"
                                            + "                return true;\n"
                                            + "            \n"
                                            + "        }\n"
                                            + "        System.out.println(i);\n"
                                            + "        return false;\n"
                                            + "\n"
                                            + "\n"
                                            + "    }    \n"
                                            + "    private void foo(Object o, int i)\n"
                                            + "    {\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}",
                                            
                                            /**
                                             * NoHintDueToMethodThrowingException
                                             */
                                            "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.Arrays;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    public static void main(String[] args) throws Exception {\n"
                                            + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                                            + "    }\n"
                                            + "\n"
                                            + "   \n"
                                            + "    public Boolean test(List<Integer> ls) throws Exception {\n"
                                            + "        Integer i=0;\n"
                                            + "        \n"
                                            + "        for(Integer l : ls)\n"
                                            + "        {         \n"
                                            + "            foo(l,1);\n"
                                            + "            if(l==null)\n"
                                            + "            {                           \n"
                                            + "                continue;\n"
                                            + "            }\n"
                                            + "            else if(l.toString()==null)\n"
                                            + "                return true;\n"
                                            + "            \n"
                                            + "        }\n"
                                            + "        System.out.println(i);\n"
                                            + "        return false;\n"
                                            + "\n"
                                            + "\n"
                                            + "    }    \n"
                                            + "    private void foo(Object o, int i) throws Exception\n"
                                            + "    {\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}"
                                            ,
                                            
                                            /**
                                             * NoHintDueToExplicitThrow
                                             */
                                            "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.Arrays;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    public static void main(String[] args) throws Exception {\n"
                                            + "        new TestDemo().test(Arrays.asList(1, 2, 3,7));\n"
                                            + "    }\n"
                                            + "\n"
                                            + "   \n"
                                            + "    public Boolean test(List<Integer> ls) throws Exception {\n"
                                            + "        Integer i=0;\n"
                                            + "        \n"
                                            + "        for(Integer l : ls)\n"
                                            + "        {         \n"
                                            + "            throw new Exception();            \n"
                                            + "            \n"
                                            + "        }\n"
                                            + "        System.out.println(i);\n"
                                            + "        return false;\n"
                                            + "\n"
                                            + "\n"
                                            + "    }    \n"
                                            + "    private void foo(Object o, int i) throws Exception\n"
                                            + "    {\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}"
                                            ,
                                            
                                            /**
                                             * NPEForReturnWithExpressions
                                             */
                                            "package testdemo;\n" +
                                            "import java.util.List;" +
                                            "class TestDemo {\n" +
                                            "    public void test(List<Integer> ls) throws Exception {\n" +
                                            "        for(Integer l : ls) {\n" +
                                            "            return ;\n" +
                                            "        }\n" +
                                            "    }\n" +
                                            "}",
                                            
                                            /**
                                             * NoHintDueToReducers
                                             */
                                           "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.ArrayList;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "/**\n"
                                            + " *\n"
                                            + " * @author alexandrugyori\n"
                                            + " */\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    /**\n"
                                            + "     * @param args the command line arguments\n"
                                            + "     */\n"
                                            + "    public static void main(String[] args) {\n"
                                            + "        // TODO code application logic here\n"
                                            + "        List<String> strs = new ArrayList<String>();\n"
                                            + "        int i = 0;\n"
                                            + "        int j = 0;\n"
                                            + "        for(String str: strs)\n"
                                            + "        {\n"
                                            + "            if(str!=null){\n"
                                            + "                str.toString();\n"
                                            + "            i++;\n"
                                            + "            j++;\n"
                                            + "            }\n"
                                            + "            //j++;\n"
                                            + "        }\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}"
                                            ,
                                            
                                            /**
                                             * NoHintDueToReturningIf
                                             */
                                           "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.ArrayList;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "/**\n"
                                            + " *\n"
                                            + " * @author alexandrugyori\n"
                                            + " */\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    /**\n"
                                            + "     * @param args the command line arguments\n"
                                            + "     */\n"
                                            + "    public boolean b() {\n"
                                            + "        // TODO code application logic here\n"
                                            + "        List<String> strs = new ArrayList<String>();\n"
                                            + "        int i = 0;\n"
                                            + "        int j = 0;\n"
                                            + "        for(String str: strs)\n"
                                            + "        {            \n"
                                            + "            if(str!=null){\n"
                                            + "                return true;\n"
                                            + "            }\n"
                                            + "            System.out.println(\"gugu\");\n"
                                            + "        }\n"
                                            + "        return false;\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}"
                                            ,
                                            
                                            /**
                                             * NoHintDueToReturnNothing
                                             */
                                           "package testdemo;\n"
                                            + "\n"
                                            + "import java.util.ArrayList;\n"
                                            + "import java.util.List;\n"
                                            + "\n"
                                            + "/**\n"
                                            + " *\n"
                                            + " * @author alexandrugyori\n"
                                            + " */\n"
                                            + "class TestDemo {\n"
                                            + "\n"
                                            + "    /**\n"
                                            + "     * @param args the command line arguments\n"
                                            + "     */\n"
                                            + "    public void b() {\n"
                                            + "        // TODO code application logic here\n"
                                            + "        List<String> strs = new ArrayList<String>();\n"
                                            + "        int i = 0;\n"
                                            + "        int j = 0;\n"
                                            + "        for(String str: strs)\n"
                                            + "        {            \n"
                                            + "            if(str!=null){\n"
                                            + "                return;\n"
                                            + "            }\n"
                                            + "        }\n"
                                            + "        return;\n"
                                            + "        \n"
                                            + "    }\n"
                                            + "}"
                                            
                                            })
	public void testExplicitEncoding_donttouch(String dontchange) throws Exception {
		IPackageFragment pack= context.fSourceFolder.createPackageFragment("testdemo", false, null);
		ICompilationUnit cu= pack.createCompilationUnit("TestDemo.java",
				dontchange,
				false, null);

		context.enable(MYCleanUpConstants.USEFUNCTIONALLOOP_CLEANUP);

		context.assertRefactoringHasNoChange(new ICompilationUnit[] { cu });
	}
}
